#!/bin/bash

# Copyright 2018 Pieter Hijma

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This script exports .org files to .html files using Emacs.  Emacs will
# automatically install the package htmlize to create colored output for source
# code.  The script below will set the faces of the fonts for colored output.

usage() {
    echo "Usage: $(basename $0) <org-file>"
}


compute_path() {
    local path=$1
    if [ "${path:0:1}" = "/" ]
    then    
	echo $path
    else
	echo $(pwd)/$path
    fi
}


export_the_file() {
    local org_file=$1

    emacs --batch --eval "(progn
     (require 'org)
     (require 'ob)
     (setq make-backup-files nil)
     (find-file \"$org_file\")
     (org-latex-export-to-pdf))"
}

if [ $# = 1 ]
then
    export_the_file $*
else
    usage
    exit 1
fi
